[project]
name = "ss-image-processor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.8"
dependencies = [
    "rich>=14.1.0",
    "pillow>=10.0.0",
    "opencv-python>=4.12.0.88",
    "numpy>=2.2.6",
]
