[project]
name = "ss-image-processor"
version = "0.1.0"
description = "Python tool for converting image sequences to WebP/AVIF format"
requires-python = ">=3.10"
dependencies = [
    "pillow>=10.0.0",
    "opencv-python>=4.12.0.88",
    "numpy>=2.2.6",
]
